# -*- coding: utf-8 -*-
"""魔流 · api —— API 路由注册与分发（get_api）。

（由原 `__init__.py` 拆分为 mixin，逐字搬运，行为不变。）
"""

from datetime import datetime
from typing import Any, Dict, List


from ..recommend import recognize


class ApiMixin:
    """api 功能集（原 MagicFlow 方法原样搬入）。"""

    def get_api(self) -> List[Dict[str, Any]]:
        """注册 Vue 工作台使用的魔流任务 API"""
        return [
            {
                "path": "/pool",
                "endpoint": self.pool_info,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "池盘空间（按目录分池：总量/已用/80% 阈值下的可占体积）",
            },
            {
                "path": "/site/seeds",
                "endpoint": self.get_site_seeds,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "站点级种子报表（逐条种子状态：分类/保护/账单/qB）",
            },
            {
                "path": "/hr/bills",
                "endpoint": self.get_hr_bills,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "H&R 账单按站分组（欠债/状态分布/need_left/in_qb/missing/per_torrent_hr/规则来源）",
            },
            {
                "path": "/status",
                "endpoint": self.get_status,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "获取魔流总览",
            },
            {
                "path": "/pv",
                "endpoint": self.get_pv_ledger,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "站点 PV 账本:每站每天耗了多少配额(可查历史)",
            },
            {
                "path": "/pv/budget",
                "endpoint": self.set_pv_budget,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "设置站点 PV 日预算(0=不限)",
            },
            {
                "path": "/debug/sitecap",
                "endpoint": self.debug_site_caps,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "站点类型/能力识别结果(probe=true 时联网探测)",
            },
            {
                "path": "/debug/mpsearch",
                "endpoint": self.debug_mp_search,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:调 MP 自带搜索看签名兼容性/免费且有源命中(1 PV/站)",
            },
            {
                "path": "/debug/np-main",
                "endpoint": self.debug_np_main,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "临时诊断:browse/debug 通道抓同一页的内容与自解析对比",
            },
            {
                "path": "/debug/cache",
                "endpoint": self.debug_cache,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:查看/丢弃站点抓取缓存(drop=<key> 强制下轮重抓)",
            },
            {
                "path": "/debug/crossseed",
                "endpoint": self.debug_crossseed,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:拿本任务候选当「本站非免费」跑一遍跨站选源(dry-run,add=true 才真下)",
            },
            {
                "path": "/crossseed",
                "endpoint": self.get_crossseed,
                "methods": ["GET", "POST"],
                "auth": "bear",
                "summary": "跨站免费取种:待回辅队列 + 启用任务(action=clear 清空队列)",
            },
            {
                "path": "/deck",
                "endpoint": self.deck_info,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "满魔套牌存档（mf_deck，§5.2）：按套牌汇总（site_id 可过滤）",
            },
            {
                "path": "/deck/sync",
                "endpoint": self.deck_sync,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "把当前在岗套牌写回存档（task_id 可空=全部 bonus 任务；连续 N 轮不变→满魔冻结）",
            },
            {
                "path": "/deck/apply",
                "endpoint": self.deck_apply,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "复用期：按存档把本机在种的牌重新纳管（零下载；apply=false 只预览）",
            },
            {
                "path": "/deck/delete",
                "endpoint": self.deck_delete,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "删掉一套牌存档（deck_id）",
            },
            {
                "path": "/ondemand",
                "endpoint": self.on_demand,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "点播（§1 权威来源 1）：片名/豆瓣·TMDB·IMDB 链接 → 选源（免费优先）→ 下载 → 直接转「资源」",
            },
            {
                "path": "/debug/store",
                "endpoint": self.debug_store,
                "methods": ["GET", "POST"],
                "auth": "bear",
                "summary": "状态存储健康度(action=flush 落盘 / drop-hot 清热层键验证回灌)",
            },
            {
                "path": "/debug/torrents",
                "endpoint": self.debug_qb_torrents,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:列出下载器全部种子并按标签分组(只读)",
            },
            {
                "path": "/debug/delete-gate",
                "endpoint": self.debug_delete_gate,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:查询删除闸门(hashes 逗号分隔 → 返回被硬保护拦截的子集)",
            },
            {
                "path": "/debug/swap",
                "endpoint": self.debug_swap,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:自动换种干跑(不落盘;task_id=空则全任务)",
            },
            {
                "path": "/debug/traffic",
                "endpoint": self.debug_traffic,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:未知流量审计（无魔流标签的种 + 单种限速分布）",
            },
            {
                "path": "/debug/seedlimit",
                "endpoint": self.debug_seed_limit,
                "methods": ["GET", "POST"],
                "auth": "bear",
                "summary": "诊断:解除全部单种上传限速（0 = 不限）",
            },
            {
                "path": "/debug/emit-transfer",
                "endpoint": self.debug_emit_transfer,
                "methods": ["GET", "POST"],
                "auth": "bear",
                "summary": "诊断:手工投递 TransferComplete 事件(验证库记链路)",
            },
            {
                "path": "/debug/file",
                "endpoint": self.debug_read_file,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:读取容器内文本文件片段(白名单 /app /config /core,只读)",
            },
            {
                "path": "/debug/fs",
                "endpoint": self.debug_fs,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:查看路径是否在库/是否硬链接(只读元数据)",
            },
            {
                "path": "/debug/qb",
                "endpoint": self.debug_qb_info,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:qBittorrent 可用信息一览(字段/属性/跟踪器/全局偏好,只读)",
            },
            {
                "path": "/debug/collect",
                "endpoint": self.debug_collect,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "采集模块观测：注册表/最近抓取/配额/worker 注册原因",
            },
            {
                "path": "/debug/fetch",
                "endpoint": self.debug_fetch_page,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:用站点 cookie 抓取页面片段(只读)",
            },
            {
                "path": "/debug/recognize",
                "endpoint": self.debug_recognize,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:识别种子名(评分/榜单/订阅)",
            },
            {
                "path": "/debug/douban",
                "endpoint": self.debug_douban,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:查豆瓣评分源(独立服务 magicflow-douban,HTTP 客户端)",
            },
            {
                "path": "/douban_service",
                "endpoint": self.douban_service_status,
                "methods": ["GET", "POST"],
                "auth": "bear",
                "summary": "豆瓣评分服务:库容量 + 后台慢爬进度(可 action=start|stop|reset)",
            },
            {
                "path": "/debug/recommend-run",
                "endpoint": self.debug_recommend_run,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "诊断:立即跑一轮推荐甄别",
            },
            {
                "path": "/debug/recommend-reset",
                "endpoint": self.debug_recommend_reset,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "诊断:清空推荐甄别结果",
            },
            {
                "path": "/debug/cloud-get",
                "endpoint": self.debug_cloud_get,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:OpenList /api/fs/get 原始响应",
            },
            {
                "path": "/debug/cloud-put",
                "endpoint": self.debug_cloud_put,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "诊断:尝试用 1KB 数据 PUT 到 OpenList(定位上传报错)",
            },
            {
                "path": "/settings",
                "endpoint": self.update_settings,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "更新魔流插件设置",
            },
            {
                "path": "/fallback",
                "endpoint": self.get_fallback_state,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "元数据兜底:配置 + 最近一次结果",
            },
            {
                "path": "/fallback/run",
                "endpoint": self.run_fallback,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "元数据兜底:立即扫描(dry_run=true 仅演练)",
            },
            {
                "path": "/live",
                "endpoint": self.get_live_state,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "站点实时数据 + 流量监控(直连站点,非 MP 6h 快照)",
            },
            {
                "path": "/exam",
                "endpoint": self.get_exam_state,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "新手考核汇总 + 一键起任务预演(已通过的默认不返回)",
            },
            {
                "path": "/exam/act",
                "endpoint": self.exam_act,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "新手考核:一键起任务(需 confirm=true)",
            },
            {
                "path": "/signin",
                "endpoint": self.get_signin_state,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "站点签到/登录:今日状态 + 近 7 天记录(借鉴「站点自动签到」插件)",
            },
            {
                "path": "/signin/run",
                "endpoint": self.run_signin,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "站点签到/登录:立即执行一次(kind=sign|login)",
            },
            {
                "path": "/cloud",
                "endpoint": self.get_cloud_state,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "云盘归档:配置 + 最近计划/结果 + 归档记录",
            },
            {
                "path": "/cloud/test",
                "endpoint": self.test_cloud,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "云盘归档:连通性自检(OpenList 存储/挂载)",
            },
            {
                "path": "/cloud/plan",
                "endpoint": self.plan_cloud,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "云盘归档:生成归档计划(只读,不写不删)",
            },
            {
                "path": "/cloud/upload",
                "endpoint": self.upload_cloud,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "云盘归档:上传单个文件(dry_run=true 仅演练)",
            },
            {
                "path": "/cloud/run",
                "endpoint": self.run_cloud,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "云盘归档:跑一轮(默认 dry_run,不删本地)",
            },
            {
                "path": "/cloud/clear",
                "endpoint": self.clear_cloud,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "云盘归档:清空归档记录(不动文件)",
            },
            {
                "path": "/downloader/prefs",
                "endpoint": self.get_downloader_prefs,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "读取下载器全局参数",
            },
            {
                "path": "/downloader/prefs",
                "endpoint": self.update_downloader_prefs,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "写入下载器全局参数",
            },
            {
                "path": "/downloader/paths",
                "endpoint": self.update_downloader_paths,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "写入下载器全局目录",
            },
            {
                "path": "/defaults",
                "endpoint": self.get_defaults,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "读取默认任务模板",
            },
            {
                "path": "/defaults",
                "endpoint": self.update_defaults,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "保存默认任务模板",
            },
            {
                "path": "/iyuu/sites",
                "endpoint": self.get_iyuu_sites,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "列出 MoviePilot 已配置站点 + 当前 IYUU 设置(供密钥表)",
            },
            {
                "path": "/iyuu/test",
                "endpoint": self.test_iyuu,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "测试 IYUU Token 连通性",
            },
            {
                "path": "/reseed",
                "endpoint": self.get_reseed,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "全站辅种:状态(站点/配额/云端缓存/账本)",
            },
            {
                "path": "/reseed",
                "endpoint": self.update_reseed,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "全站辅种:配置(开关/干跑/站点白名单/限量)",
            },
            {
                "path": "/reseed/probe",
                "endpoint": self.reseed_probe,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "全站辅种:逐站下载链诊断(模板/口令/cookie)",
            },
            {
                "path": "/reseed/run",
                "endpoint": self.run_reseed,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "全站辅种:立刻跑一轮(dry=true 只算不挂)",
            },
            {
                "path": "/events",
                "endpoint": self.get_events,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "结构化事件流(journal 读模型+本地补充;支持 since/limit/kind/task_id/level)",
            },
            {
                "path": "/debug/events",
                "endpoint": self.debug_events,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "事件流诊断:数量(分 kind/level)/本地缓冲/已知分类",
            },
            {
                "path": "/health",
                "endpoint": self.get_health,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "健康自检:任务失败/卡死·时魔下滑·磁盘贴上限(按严重度排序)",
            },
            {
                "path": "/trend",
                "endpoint": self.get_trend,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "趋势观测:每小时采样(站点/任务口径时魔·做种数·体积)最近 7 天",
            },
            {
                "path": "/debug/trend",
                "endpoint": self.debug_trend,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "趋势诊断:序列数/点数/最后采样时间",
            },
            {
                "path": "/silent/pool",
                "endpoint": self.silent_pool,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "静默池全局视图（概览/按站/条目/记录，只读）",
            },
            {
                "path": "/claim",
                "endpoint": self.get_claim_state,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "认领:状态(能力/可认领/已认领/账本/记录)",
            },
            {
                "path": "/claim/run",
                "endpoint": self.run_claim,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "认领:跑一轮(默认干跑;write=1&confirm=1 才真写)",
            },
            {
                "path": "/claim/do",
                "endpoint": self.claim_do,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "认领:手动认领单条(需 confirm=1)",
            },
            {
                "path": "/claim/abandon",
                "endpoint": self.claim_abandon,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "认领:放弃认领(需 confirm=1;无接口模板则不执行)",
            },
            {
                "path": "/debug/claim",
                "endpoint": self.debug_claim,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "认领:诊断(能力探测/可认领/账本/适配器)",
            },
            {
                "path": "/migrate",
                "endpoint": self.get_migrate,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "账本迁移:状态(完成戳/游标/阶段计划)",
            },
            {
                "path": "/migrate",
                "endpoint": self.run_migrate,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "账本迁移:推一块(force=true 忽略完成戳重推)",
            },
            {
                "path": "/recommend",
                "endpoint": self.get_recommend_list,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "列出推荐甄别结果",
            },
            {
                "path": "/recommend/{hash}/confirm",
                "endpoint": self.confirm_recommend,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "确认推荐(自动整理入库)",
            },
            {
                "path": "/recommend/{hash}/dismiss",
                "endpoint": self.dismiss_recommend,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "忽略推荐并删除",
            },
            {
                "path": "/recommend/{hash}/import",
                "endpoint": self.import_recommend,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "手动整理入库",
            },
            {
                "path": "/recommend/batch_import",
                "endpoint": self.import_recommend_batch,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "批量整理入库(hashes=… 或 all=1)",
            },
            {
                "path": "/tasks",
                "endpoint": self.create_task,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "创建魔流任务",
            },
            {
                "path": "/tasks/{task_id}",
                "endpoint": self.get_task_detail,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "获取魔流任务详情",
            },
            {
                "path": "/tasks/{task_id}",
                "endpoint": self.update_task,
                "methods": ["PUT"],
                "auth": "bear",
                "summary": "更新魔流任务",
            },
            {
                "path": "/tasks/{task_id}",
                "endpoint": self.delete_task,
                "methods": ["DELETE"],
                "auth": "bear",
                "summary": "删除魔流任务",
            },
            {
                "path": "/tasks/{task_id}/state",
                "endpoint": self.update_task_state,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "启用或暂停魔流任务",
            },
            {
                "path": "/tasks/{task_id}/run",
                "endpoint": self.run_task,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "立即执行一轮魔力优化",
            },
            {
                "path": "/tasks/{task_id}/bonus",
                "endpoint": self.get_task_bonus,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "获取任务做种魔力明细",
            },
            {
                "path": "/tasks/{task_id}/candidates",
                "endpoint": self.get_task_candidates,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "获取站点候选种子及魔力评分",
            },
            {
                "path": "/tasks/{task_id}/backfill-pages",
                "endpoint": self.backfill_torrent_pages,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "回填存量托管种子的详情页链接(供促销核对)",
            },
            {
                "path": "/backfill-pages",
                "endpoint": self.backfill_batch,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "对所有任务批量回填详情页链接",
            },
            {
                "path": "/tasks/{task_id}/preview",
                "endpoint": self.preview_cleanup,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "预览一轮删种名单",
            },
            {
                "path": "/tasks/{task_id}/operations",
                "endpoint": self.get_operations,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "获取任务操作记录",
            },
            {
                "path": "/operations",
                "endpoint": self.get_all_operations,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "获取全部任务的操作记录（主页全局视图）",
            },
            {
                "path": "/features",
                "endpoint": self.features_overview,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "功能注册表（契约③）：登记项 + 开启状态",
            },
            {
                "path": "/tasks/{task_id}/torrents/{hash}/protect",
                "endpoint": self.protect_torrent,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "手动保留种子",
            },
            {
                "path": "/tasks/{task_id}/torrents/{hash}/unprotect",
                "endpoint": self.unprotect_torrent,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "取消保留种子",
            },
            {
                "path": "/tasks/{task_id}/torrents/{hash}/delete",
                "endpoint": self.manual_delete_torrent,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "手动删除种子",
            },
            {
                "path": "/tasks/{task_id}/torrents/{hash}/pause",
                "endpoint": self.pause_torrent,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "暂停种子",
            },
            {
                "path": "/tasks/{task_id}/torrents/{hash}/resume",
                "endpoint": self.resume_torrent,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "恢复做种",
            },
            {
                "path": "/tasks/{task_id}/torrents/{hash}/recheck",
                "endpoint": self.recheck_torrent,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "强制校验种子",
            },
            {
                "path": "/tasks/{task_id}/torrents/batch",
                "endpoint": self.batch_torrents,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "批量操作托管种子",
            },
            {
                "path": "/rules",
                "endpoint": self.get_site_rules,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "站点规则库(H&R/保种时长/做种上限)",
            },
            {
                "path": "/tasks/{task_id}/handover",
                "endpoint": self.get_task_handover,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "删除任务前：预览名下种子可交棒给谁 / 有多少",
            },
            {
                "path": "/tasks/{task_id}/handover",
                "endpoint": self.post_task_handover,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "把任务名下种子交棒给其它任务 / 退回静默池",
            },
            {
                "path": "/tags",
                "endpoint": self.get_tag_model,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "标签模型：状态账本/文件组/分拣规则/迁移预演",
            },
            {
                "path": "/tags/set",
                "endpoint": self.set_tag_state,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "手动设置种子状态（改标签 + 写账本）",
            },
            {
                "path": "/tags/migrate",
                "endpoint": self.migrate_tags,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "老标签迁移到新命名（默认 dry-run）",
            },
            {
                "path": "/debug/candidates",
                "endpoint": self.debug_candidates,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "API 站(馒头)候选列表诊断",
            },
            {
                "path": "/debug/api",
                "endpoint": self.debug_api,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "API 通道诊断(profile/list/search/detail/dl/hash)",
            },
            {
                "path": "/debug/mteam",
                "endpoint": self.debug_mteam_api,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "馒头 API 通道诊断(profile/search/detail/dl)",
            },
            {
                "path": "/rules/probe",
                "endpoint": self.probe_site_rules,
                "methods": ["POST"],
                "auth": "bear",
                "summary": "逐站拉取站点规则并入库",
            },
            {
                "path": "/sites/{site_id}/bonus-formula",
                "endpoint": self.probe_site_formula,
                "methods": ["GET"],
                "auth": "bear",
                "summary": "抓取站点魔力公式与参数(诊断)",
            },
            {
                "path": "/rescue",
                "endpoint": self.rescue,
                "methods": ["GET", "POST"],
                "auth": "bear",
                "summary": "死种补源：停滞欠 H&R 的种从他站无 H&R 站补下同 Release(action=scan 只读预览 / apply 执行需 confirm=1)",
            },
        ]
